// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApuujr2S1GdhBnY_xiCxljS1KMfGCJogI',
    appId: '1:898880401044:web:424b096c85d12805078e81',
    messagingSenderId: '898880401044',
    projectId: 'spotify-e4906',
    authDomain: 'spotify-e4906.firebaseapp.com',
    storageBucket: 'spotify-e4906.appspot.com',
    measurementId: 'G-R16JKX6SXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe-xTrpK5piMrjpYla20UE-wr0KhqmGcA',
    appId: '1:898880401044:android:91c051285d650998078e81',
    messagingSenderId: '898880401044',
    projectId: 'spotify-e4906',
    storageBucket: 'spotify-e4906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCL39Ya_bF-eI5lygQZUkQia2YnWT3iS8',
    appId: '1:898880401044:ios:a5f1a836bdbea633078e81',
    messagingSenderId: '898880401044',
    projectId: 'spotify-e4906',
    storageBucket: 'spotify-e4906.appspot.com',
    iosBundleId: 'com.example.spotifyFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCL39Ya_bF-eI5lygQZUkQia2YnWT3iS8',
    appId: '1:898880401044:ios:52fb0228e5af4003078e81',
    messagingSenderId: '898880401044',
    projectId: 'spotify-e4906',
    storageBucket: 'spotify-e4906.appspot.com',
    iosBundleId: 'com.example.spotifyFinal.RunnerTests',
  );
}
